name: wgpu-d CI

on: push
#   schedule:
#   - cron: '0 0 * * SUN'

jobs:
  test:
    name: Tests

    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]
        # TODO: os: [ubuntu-latest, macos-12, windows-latest]
        compiler: [ldc-1.36.0, dmd-2.107.0]
        # FIXME: ImportC doesn't emit `struct` constructors?
        # Undefined symbols for architecture x86_64:
        #  "__C.WGPURenderPassDescriptor.__initwgpu_bindings", referenced from:
        #      @trusted wgpu.api.RenderPass wgpu.api.CommandEncoder.beginRenderPass(const(__C.WGPURenderPassDescriptor)) in wgpu-d-test-unittest.o
        exclude:
        - os: macos-12
          compiler: dmd-2.107.0

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.compiler }}
    # - name: Install *nix Dependencies
    #   if: runner.os == 'Linux'
    #   run: sudo apt-get install --quiet -y libglfw3 libglfw3-dev
    - name: Lint
      run: dub run dscanner -- lint -f github source
    # - name: Integration Test
    #   run: dub build wgpu-d:headless
    - name: Test
      run: make cover
    - name: Upload Coverage to Codecov
      if: success()
      run: bash <(curl -s https://codecov.io/bash)
