name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Dependencies
        runs-on: macos-latest
        run: brew install gnu-sed
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-1.28.0
      - name: Build Documentation
        run: make docs

      - name: GitHub Pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2.1.2
        with:
          target_branch: gh-pages
          build_dir: docs
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
